name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level to use'
        type: choice        
        options:
          - debug
          - info
          - warning
        required: true
        default: 'info'
      environment:
        type: environment
        description: 'Environment to deploy to'
        required: true
      matrix:
        description: 'Matrix of values to run the job with'
        type: string
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}
        
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ matrix.LEVEL }}
          ENVIRONMENT: ${{ matrix.ENVIRONMENT }}